# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM Architecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM Architecture

pod 'Alamofire', '~> 5.2'

  target 'MVVM ArchitectureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM ArchitectureUITests' do
    # Pods for testing
  end

end
